package(default_visibility = ["//visibility:public"])
load("@rules_arm_clang//:gen.bzl", "gen_bin", "gen_asm", "gen_hex")

cc_library(
    name = "example",
    srcs = [
        "lib.c",
        "lib.cc",
    ],
)
